<?php

namespace ContainerZgVbQa7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O84SUkkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.O84SUkk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.O84SUkk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\PostController::batiment' => ['privates', '.service_locator.BpdDjdR', 'get_ServiceLocator_BpdDjdRService', true],
            'App\\Controller\\PostController::bois' => ['privates', '.service_locator.BpdDjdR', 'get_ServiceLocator_BpdDjdRService', true],
            'App\\Controller\\PostController::edit' => ['privates', '.service_locator.4WI1Dtz', 'get_ServiceLocator_4WI1DtzService', true],
            'App\\Controller\\PostController::exploitation' => ['privates', '.service_locator.BpdDjdR', 'get_ServiceLocator_BpdDjdRService', true],
            'App\\Controller\\PostController::index' => ['privates', '.service_locator.BpdDjdR', 'get_ServiceLocator_BpdDjdRService', true],
            'App\\Controller\\PostController::prairie' => ['privates', '.service_locator.BpdDjdR', 'get_ServiceLocator_BpdDjdRService', true],
            'App\\Controller\\PostController::show' => ['privates', '.service_locator.Xf_chUG', 'get_ServiceLocator_XfChUGService', true],
            'App\\Controller\\PostController::terrain' => ['privates', '.service_locator.BpdDjdR', 'get_ServiceLocator_BpdDjdRService', true],
            'App\\Controller\\SecurityController::registration' => ['privates', '.service_locator.wU7gDXT', 'get_ServiceLocator_WU7gDXTService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Controller\\PostController:batiment' => ['privates', '.service_locator.BpdDjdR', 'get_ServiceLocator_BpdDjdRService', true],
            'App\\Controller\\PostController:bois' => ['privates', '.service_locator.BpdDjdR', 'get_ServiceLocator_BpdDjdRService', true],
            'App\\Controller\\PostController:edit' => ['privates', '.service_locator.4WI1Dtz', 'get_ServiceLocator_4WI1DtzService', true],
            'App\\Controller\\PostController:exploitation' => ['privates', '.service_locator.BpdDjdR', 'get_ServiceLocator_BpdDjdRService', true],
            'App\\Controller\\PostController:index' => ['privates', '.service_locator.BpdDjdR', 'get_ServiceLocator_BpdDjdRService', true],
            'App\\Controller\\PostController:prairie' => ['privates', '.service_locator.BpdDjdR', 'get_ServiceLocator_BpdDjdRService', true],
            'App\\Controller\\PostController:show' => ['privates', '.service_locator.Xf_chUG', 'get_ServiceLocator_XfChUGService', true],
            'App\\Controller\\PostController:terrain' => ['privates', '.service_locator.BpdDjdR', 'get_ServiceLocator_BpdDjdRService', true],
            'App\\Controller\\SecurityController:registration' => ['privates', '.service_locator.wU7gDXT', 'get_ServiceLocator_WU7gDXTService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
        ], [
            'App\\Controller\\PostController::batiment' => '?',
            'App\\Controller\\PostController::bois' => '?',
            'App\\Controller\\PostController::edit' => '?',
            'App\\Controller\\PostController::exploitation' => '?',
            'App\\Controller\\PostController::index' => '?',
            'App\\Controller\\PostController::prairie' => '?',
            'App\\Controller\\PostController::show' => '?',
            'App\\Controller\\PostController::terrain' => '?',
            'App\\Controller\\SecurityController::registration' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\PostController:batiment' => '?',
            'App\\Controller\\PostController:bois' => '?',
            'App\\Controller\\PostController:edit' => '?',
            'App\\Controller\\PostController:exploitation' => '?',
            'App\\Controller\\PostController:index' => '?',
            'App\\Controller\\PostController:prairie' => '?',
            'App\\Controller\\PostController:show' => '?',
            'App\\Controller\\PostController:terrain' => '?',
            'App\\Controller\\SecurityController:registration' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
