<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPLakhhy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPLakhhy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPLakhhy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPLakhhy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPLakhhy\App_KernelDevDebugContainer([
    'container.build_hash' => 'PLakhhy',
    'container.build_id' => '1dfaf7b0',
    'container.build_time' => 1672952289,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPLakhhy');
