<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNvxdlKW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNvxdlKW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNvxdlKW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNvxdlKW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNvxdlKW\App_KernelDevDebugContainer([
    'container.build_hash' => 'NvxdlKW',
    'container.build_id' => '754c0e21',
    'container.build_time' => 1672447401,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNvxdlKW');
