<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXNxRJca\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXNxRJca/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXNxRJca.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXNxRJca\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXNxRJca\App_KernelDevDebugContainer([
    'container.build_hash' => 'XNxRJca',
    'container.build_id' => '278ad5e1',
    'container.build_time' => 1672418209,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXNxRJca');
