<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNHUu6Ad\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNHUu6Ad/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNHUu6Ad.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNHUu6Ad\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNHUu6Ad\App_KernelDevDebugContainer([
    'container.build_hash' => 'NHUu6Ad',
    'container.build_id' => '5ea793f2',
    'container.build_time' => 1673171018,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNHUu6Ad');
